= Annotation Editor Remote Operation (AERO) Protocol

== Introduction

The purpose of AERO is to embed a (generic) annotation editor within a service NLP/TDM infrastructure. The protocol focuses on actions triggered by the infrastructure. No dependencies of the annotation editor on the infrastructure are introduced. This ensures that the annotation editor can be embedded in various different infrastructures that support AERO.

An infrastructure often offers multiple services, e.g. a registry/catalog and a storage system. If an annotation editor needs to be aware of these services, it creates a strong coupling of the editor with the surrounding platform and actions such as opening a document or searching for a document can easily require replicating a significant part of the functionality of these other services. Hence, it is more sensible to design a protocol that allows embedding arbitrary annotation editors in a platform without introducing dependencies on the surrounding platform.

Many annotation editors - even web-based ones - do not offer any remote API at all. They cannot be embedded in an infrastructure. Transferring data between the infrastructure and the editor always requires the user importing/exporting the data. AERO provides a set of calls and data structures that enable a basic set of interactions related to managing project, documents, annotations, and curated annotations. As such, it is suitable for annotation editors that support these concepts, e.g. WebAnno, AlvisAE, brat, etc.

== API

This section explains the data structures and API calls defined by AERO.

=== Data Structures

==== AERO JSON response

The response provides an envelop for a returned data structure. In addition to the actual response in the "body", the envelope contains a field for “messages”. Example:

[source,json]
----
{
  "messages": [
    { "level": "WARN", "text": "Internal error while accessing document 10.",
  ],
  "body": [
    {
      "id": "32",
      "name": "sample.txt",
      "state": "CURATION_FINISHED"
    },
    {
      "id": "33",
      "name": "essay001.xmi",
      "state": "NEW"
    }
  ]
}
----

A message always contains a "level" and a "text" field. The text must be a string. Acceptable values for the "level" field are the strings:

.Log levels
* `ERROR` - if there is an error, then typically the body is empty.
* `WARN` - if there is a warning, then the body might be incomplete. 
* `INFO` - an informative message, typically a confirmation message that the action requested by the client has been performed.
* `DEBUG` - an AERO server should never generate debug messages unless specifically configured to do so by its administrator

==== Constant Values

.Document status
* `NEW`
* `ANNOTATION-IN-PROGRESS`
* `ANNOTATION-COMPLETE`
* `CURATION-IN-PROGRESS`
* `CURATION-COMPLETE`

.Annotation status
* `NEW`
* `LOCKED`
* `IN-PROGRESS`
* `COMPLETE`

=== Calls

This section explains the API calls defined by AERO. All the calls are relative to a base URL which depends on the URL where the annotation tool is hosted. It is recommended but not mandatory that the URL includes `aero` and `v1`, e.g. `http://annotool.myorg.com/api/aero/v1/`.

==== Projects

include::{include-dir}/calls/projects_list.adoc[]

include::{include-dir}/calls/projects_create.adoc[]

include::{include-dir}/calls/projects_delete.adoc[]

include::{include-dir}/calls/projects_import.adoc[]

include::{include-dir}/calls/projects_export.adoc[]

==== Documents

include::{include-dir}/calls/documents_list.adoc[]

include::{include-dir}/calls/documents_create.adoc[]

include::{include-dir}/calls/documents_read.adoc[]

include::{include-dir}/calls/documents_delete.adoc[]

==== Annotations

include::{include-dir}/calls/annotations_list.adoc[]

include::{include-dir}/calls/annotations_create.adoc[]

include::{include-dir}/calls/annotations_read.adoc[]

include::{include-dir}/calls/annotations_delete.adoc[]

==== Curations

include::{include-dir}/calls/curations_list.adoc[]

include::{include-dir}/calls/curations_create.adoc[]

include::{include-dir}/calls/curations_read.adoc[]

include::{include-dir}/calls/curations_delete.adoc[]

=== Event Notifications

include::{include-dir}/notifications/document_state_changed.adoc[]

